firstDraft
jupyter/jupyter_markdown pull request #1
Opened 2017-06-13 04:13 UTC by ashutoshbondre

Added 3 files:
1. spec.json (The json data)
2. script.py (The python script which generated the notebook)
3. firstDraft.ipynb (The actual notebook)

2017-06-14 19:44 UTC, ellisonbg requested changes
Talked to Ashutosh today in person. Summary of the discussion:

1. Add `%%html` cells with the converted HTML from the spec file so we can compare our generated HTML.
2. Split the notebook into a series of smaller ones, each with maybe 100 cells (the full one is quite large).
3. Add a section header for each example such as "Example 1" as a Markdown cell.

2017-06-14 22:37 UTC, mpacer reviewed
Tried to find all of the little things that will make this more portable and configurable in the long run. Some of my example code would address these issues (at least by making them top level variables instead of hard-coded values).

2017-07-08 18:46 UTC, ellisonbg approved these changes

2017-07-08 18:46 UTC, merged

2023-09-15 08:52 UTC, Mhtpyurt reviewed
Sevdiğim

2023-09-15 08:52 UTC, Mhtpyurt commented on firstDraft.ipynb
H

2023-09-15 08:52 UTC, Mhtpyurt commented on firstDraft.ipynb
Aşk